### ISSUE TITLE
Stalactites

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#11]
![download](https://user-images.githubusercontent.com/61751485/136730168-aaa9869b-e486-44d2-ad51-91603fcd5b77.jpg)

**Comment by EvanSkiStudios** [comment]
dripstone should be like using flint to make arrows

**Comment by Mercerenies** [comment]
Stalactite spawning happens 2.5 times less often (was every 4 ticks, now is every 10 ticks), and pointed dripstone can be used to make arrows.
