### ISSUE TITLE
Blaze Eyes

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#111]
Ender pearl + flint & steel makes a blaze eye. When thrown in the nether, blaze eyes point you to a nether fortress.

**Comment by Mercerenies** [comment]
Will probably require nms. This guy did it: https://dev.bukkit.org/projects/enderchanger

**Comment by Mercerenies** [comment]
Implemented in ffb8e65

@EvanSkiStudios Custom tag is `blaze_eye_tag` (inside the Turtle Troll namespace), and the model ID is 1. Go to town! :D

**Comment by EvanSkiStudios** [comment]
I've added it to the resource pack
