### ISSUE TITLE
sfx for when trivia comes on

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#123]

**Comment by Mercerenies** [comment]
@EvanSkiStudios Can you add a good sound for this to the texture pack and tell me what it's called so I can play it from Turtle's Troll? Something to notify all players that there's a trivia question that just popped up.

**Comment by EvanSkiStudios** [comment]
trivia.ogg

filepath:
sounds/custom/event/trivia.ogg

json:
```
	"custom.event.trivia": { 
		"category": "player", "sounds": [ "custom/events/trivia" ]
	}
```
