### ISSUE TITLE
God Demand Effects

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#148]
I have some things we (meaning mostly you) can do to make the demands look / effect better

for the start, for the demands when they happen when they are complete when they see feet, ect

We can use TITLES

```java
int fadeIn = 10; //In ticks
int stay = 70;
int fadeOut = 20;
player.sendTitle(ChatColor.RED + "The Gods are angry!", "No one shall sleep tonight!", fadeIn, stay, fadeOut);
player.sendTitle(ChatColor.GREEN + "The Gods are appeased!", "Everyone is free to sleep!", fadeIn, stay, fadeOut);
player.sendTitle(ChatColor.YELLOW + "The Gods have a demand!", ChatColor.RED + "Today, the gods would like to see someone die ${description}", fadeIn, stay, fadeOut);
 ```

Here is an example of how to use titles
            
If you have ever played a mini game on some minecraft server, a title is a literal in your face message, with big text (title) and smaller text (subtitle)

then of course fade effects

-Im getting sounds ready for these as well and will let you know the code for them like for trivia

**Comment by EvanSkiStudios** [comment]
sounds

json
```
"custom.event.gods.angry": { 
  "category": "player", "sounds": [ "custom/event/Gods/angry" ]
},
"custom.event.gods.demand": { 
  "category": "player", "sounds": [ "custom/event/Gods/demand" ]
},
"custom.event.gods.pleased": { 
  "category": "player", "sounds": [ "custom/event/Gods/pleased" ]
}
```
filepath:
sounds/custom/event/gods/
angry, demand, please

**Comment by Mercerenies** [comment]
Implemented as requested (both titles and sounds). Bowser currently only has one title (for introducing his effect) and no sounds, but the gods are done.
