### ISSUE TITLE
freeze to death in cold biomes

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#23]
so in cold biomes like tundra or ice spikes
snowy grass should be replaced with powered snow

like just the top layer because you can move through it so if all was replaced you'd fall a bit
(Dont do that, I know you, thats not a funny idea thats annoying)

but basically it would require us to wear lether in cold biomes or freeze to death

(idk if vanilla feature)
maybe fire nearby prevents the ice effect?

**Comment by Mercerenies** [comment]
dc53b7b adds climate damage if you don't have the right gear.
