### ISSUE TITLE
Dripstone arrows should be upside down

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#25]
Use a custom NBT tag to make dripstone arrows upside-down.

**Comment by EvanSkiStudios** [comment]
`minecraft:arrow{CustomModelData:8565,ud_arrow}`

CustomModelData is a built in NBT string for every item
ud_arrow is a NBT "tag"

**Comment by Mercerenies** [comment]
52c9d1b closes this
