### ISSUE TITLE
Compressed Dirt

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#31]
6 dirt can be crafted into 1 stick.

**Comment by Mercerenies** [comment]
9 dirt, actually, but potato potahto

**Comment by EvanSkiStudios** [comment]
I want to change this, so you get a custom item of "compressed dirt"

You wont be able to place it, but you can then uncraft it into 9x dirt

I'll do this in RM so you'll have to remove yours 

if your down for a new item
