### ISSUE TITLE
Every wither skeleton that spawns has a 50/50 chance to have a bow

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#34]
Test this for yourself 
Try to take on a wither skeleton with a bow in survival
and you will see why you should add this

**Comment by Mercerenies** [comment]
And with the diamond armor, at that. You're starting to turn into me >:)

**Comment by EvanSkiStudios** [comment]
only when I think it will be amusing

**Comment by Mercerenies** [comment]
Added in 24db31b
