### ISSUE TITLE
Temperature as Scoreboard

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#38]
Follow-on to #23, let's expose the player's temperature as a scoreboard to allow [Raccoon-Mischief #12](https://github.com/EvanSkiStudios/Raccoon-Mischief/issues/12) to access it.

**Comment by Mercerenies** [comment]
ad5193c creates this scoreboard. It isn't displayed on screen but it is available. A few notes
* The scoreboard is called `com.mercerenies.turtletroll.TemperatureManager.SCOREBOARD_NAME` (I wanted to make sure the name was unique, so sue me)
* The scoreboard is updated once every four seconds (that's how often I check for burn/freeze effects anyway)
* For offline players, the scoreboard will contain the last known temperature of that player
* Temperature values are measured in Celsius, where "below zero" is the threshold for freezing and "above 100" is the threshold for burning.

Closing this issue. @EvanSkiStudios, over to you.

**Comment by EvanSkiStudios** [comment]
com.mercerenies.turtletroll.TemperatureManager.SCOREBOARD_NAME

Got it

i'll see what i can do
