### ISSUE TITLE
Make silverfish burn in the daylight

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#42]
You might be able to do two checks on the silverfish entity with a listener
that checks if its in a skylight level of 15

then somehow set the entity on fire while its in that skylight value
without causing a forest fire, but I know you and you'll make it catch the ground on fire anyway

**Comment by Mercerenies** [comment]
Implemented as of 3c0e3ef.

**Comment by Mercerenies** [comment]
And no, I didn't set the ground on fire. It's ordinary entity fire, like zombies or anything else.
