### ISSUE TITLE
parrots

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#53]
parrots shouls spawn automatically tamed to the nearest player

the oarrot should fly and try to land on he shoulder of their tamed owner

if they mangae to do so
the player dies

give them speed as well so they can fly faster

**Comment by Mercerenies** [comment]
Closed. All parrots spawn in with Speed 1 and Health Boost 2 and tame to the nearest player. If they perch on your shoulder, you get Levitation 100 for 3 seconds.

Also, witches now sometimes throw parrots instead of potions.

**Comment by EvanSkiStudios** [comment]
Replace the levitation with instant damage 10
