### ISSUE TITLE
Temperature fixes

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#62]
Follow-on from #38 

We want the temp going from -10 to 10.

**Comment by EvanSkiStudios** [comment]
Here is a link to an sheet that has them all laid out
[sheet](https://docs.google.com/spreadsheets/d/16q6SINMsl8etm5Lbv-KuIodirbmXgpN0ALPJiDd8Z2Q/edit#gid=0)
I think would be the easiest way to do it, maybe you already have it like this idk but heres my thinking

200 is on fire always with and without armor (needs cooling source like ice)

100 is on fire with armor

90 - 70 is normal, no effects

50 is freezing with no armor

20 -> -5 is freezing with and without armor (needs heat source like fire)

That way I can only check certain ranges of temps to update the ui for
and it makes the temps with the biomes make more sense rather then burning alive in the mountains

if the player is a distance from fire or holding lava/torch or whatever, just set their temp to 0

visa versa for ice and such

you could also do the opposite and in cold biomes holding snow and ice makes you freeze
and hot biomes lava and ect makes you burn

Its a lot of work from both of us, but I think this is do-able and something awesome

**Comment by Mercerenies** [comment]
Alright, temperature now scales such that -10 is freezing and 10 is burning. It also takes into consideration held objects. A held "cold" object like ice or snow, protects you from hot biomes, and a held "hot" object like a lava bucket or a campfire protects you from cold biomes. Holding an object never counts against you; it can only protect you, not hurt you.

And in the current version, there are no biomes that unconditionally damage you: Every biome is either (1) you must be naked to be safe, (2) you must be clothed to be safe, or (3) moderate temperature and you're always safe.
