### ISSUE TITLE
Iron golems always spawn angry at player

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#69]
some info here
https://bukkit.org/threads/forcing-iron-golems-to-attack-players.102599/

**Comment by EvanSkiStudios** [comment]
would also be funny if you gave them the phantom speed so they always charge out from no where to the player

**Comment by Mercerenies** [comment]
See [f9964c2](https://github.com/Mercerenies/a-turtles-troll/commit/f9964c294656105ebf59da9fe7c0ce6db2ec6136). Iron golems now pursue the nearest player (they will get distracted if there's *another* hostile mob nearby, but if there's no other target, they attack you). They also perpetually have Speed 1 and Regen 1, and all iron golems spawn in riding spiders.

None of this applies to player-crafted golems, which still behave normally and will never attack a player.
