### ISSUE TITLE
Hats for everyone!

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#74]
Now that the resoucepack has hats
we should do 2 things

1. zombies should have a chance to spawn with an hat

These hats are renamed carved pumpkins that the resourcepack highjacks and remodels
(i shall provide a list of hat names)

2. seeing as carved pumpkins prevent water lightning we need to decide what to do about this
remove carved pumpkin protection?
remove the protection from renamed pumpkins?

I would like it so that a player can see a zombie with a hat they want
kill them, and get the new hat
I think it would be fun

**Comment by EvanSkiStudios** [comment]
Make an exception to pumpkins so we dont burn due to tempature

**Comment by Mercerenies** [comment]
* Zombie spawning implemented by 867bffe
* Remove protection for custom renamed pumpkins implemented by da2185b
* Temperature doesn't look for pumpkin helmets (even ordinary ones) implemented by 6973f47

Current custom hat list is enumerated at [Hats.kt](https://github.com/Mercerenies/a-turtles-troll/blob/master/src/Hats.kt#L12-L16), based on the current list I could find in Textile. If I missed anything or if you add any new ones, feel free to add them to that and make a PR (or just bug me), @EvanSkiStudios
