### ISSUE TITLE
Allays

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#75]
Allays should give you any other random item besides the one they are holding

**Comment by Mercerenies** [comment]
![](https://gifimage.net/wp-content/uploads/2017/08/maniacal-laugh-gif-9.gif)

**Comment by EvanSkiStudios** [comment]
I can change their ingame model too anything else as well

**Comment by Mercerenies** [comment]
Added. Allays always give flowers. Forever. Feel free to change their model to whatever is appropriate.
