### ISSUE TITLE
Banishment

### ISSUE THREAD

**Issue by Mercerenies** [Mercerenies/a-turtles-troll#99]
Banishment

If the gods are currently not appeased, there is a small chance that when a player dies they are sent to a superflat world. Should they die agian they are returned to their spawnpoint.

**Comment by Flipsie27** [comment]
We honestly really shouldn't do this one.

**Comment by Mercerenies** [comment]
Too late we're doing it. There's now a chance (2% on Normal difficulty) that you'll respawn in superflat every time you die.

And I never cut corners. I wanted to make sure your experience was pleasant, so I filled the superflat world with tall grass. I also spawn you 32 blocks up so you can get a good view. And I give you Slow Falling, since I wouldn't want you to hurt yourself while exploring this beautiful place. Have fun trying to die :)

![super](https://github.com/Mercerenies/a-turtles-troll/assets/8659281/e11e00f1-b8b2-468b-b9f0-a4c8f9233814)

**Comment by dolphinhats** [comment]
I love exiting in purgatory for eternity
